// Standard Convex function references; regenerated by convex dev/codegen.
import {anyApi} from 'convex/server';
import type {ApiFromModules,FilterApi,FunctionReference} from 'convex/server';
import type * as database from '../database';
export const internal=anyApi as unknown as FilterApi<ApiFromModules<{database:typeof database}>,FunctionReference<any,'internal'>>;
