// Standard Convex bindings, typed from schema. Regenerated by convex dev/codegen.
import {internalQueryGeneric,internalMutationGeneric,internalActionGeneric,httpActionGeneric} from 'convex/server';
import type {QueryBuilder,MutationBuilder,ActionBuilder,GenericActionCtx,GenericQueryCtx,GenericMutationCtx} from 'convex/server';
import type {DataModel} from './dataModel';
export const internalQuery:QueryBuilder<DataModel,'internal'>=internalQueryGeneric;
export const internalMutation:MutationBuilder<DataModel,'internal'>=internalMutationGeneric;
export const internalAction:ActionBuilder<DataModel,'internal'>=internalActionGeneric;
export const httpAction=httpActionGeneric;
export type ActionCtx=GenericActionCtx<DataModel>;
export type QueryCtx=GenericQueryCtx<DataModel>;
export type MutationCtx=GenericMutationCtx<DataModel>;
