'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,RotateCcw,Layers,Check,Timer,X,Pause,Play,ChevronDown} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {toast} from 'sonner';
import {api} from '@/lib/client';
import type {Deck,Attempt,Card} from '@/lib/types';
const shuffle=<T,>(a:T[])=>[...a].sort(()=>Math.random()-.5);
export function StudyPlayer({deck,mode,onClose,onRefresh}:{deck:Deck;mode:string;onClose:()=>void;onRefresh:()=>Promise<void>}){
 const [index,setIndex]=useState(0),[flipped,setFlipped]=useState(false),[answers,setAnswers]=useState<number[]>(deck.questions.map(()=>-1)),[result,setResult]=useState<Attempt|null>(null),[busy,setBusy]=useState(false),[reviewed,setReviewed]=useState<string[]>([]),[all,setAll]=useState(false),[seconds,setSeconds]=useState(deck.questions.length*120),[started,setStarted]=useState(false);
 const cards=deck.cards.filter(c=>all||c.due<=Date.now()).filter(c=>!reviewed.includes(c.id));const card=cards[0];const q=deck.questions[index];
 const submit=async()=>{setBusy(true);try{setResult(await api('attempt','POST',{deckId:deck.id,answers}));await onRefresh();setStarted(false)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 useEffect(()=>{if(!started||mode!=='test'||result)return;const id=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(id)},[started,mode,result]);
 useEffect(()=>{if(started&&seconds===0&&!result&&!busy){setStarted(false);void submit()}},[seconds,started,result,busy]);
 const top=<div className="player-heading"><button className="secondary" onClick={onClose}><ArrowLeft size={16}/>Study sets</button><span className="eyebrow">{mode==='test'?'AP-STYLE PRACTICE':mode.toUpperCase()}</span><h2>{deck.title}</h2></div>;
 if(mode==='match'||mode==='crash')return <section className="glass player">{top}<StudyGame deck={deck} mode={mode}/></section>;
 if(mode==='flashcards')return <section className="glass player">{top}<div className="flash-toolbar"><span>{reviewed.length} reviewed · {cards.length} remaining</span><Tabs value={all?'all':'due'} onValueChange={v=>{setAll(v==='all');setReviewed([])}}><TabsList><TabsTrigger value="due">Due today</TabsTrigger><TabsTrigger value="all">All cards</TabsTrigger></TabsList></Tabs></div>{card?<><button className={'flashcard '+(flipped?'flipped':'')} onClick={()=>setFlipped(!flipped)} aria-label="Flip flashcard"><span className="eyebrow">{flipped?'THE EXPLANATION':'BRING IT TO MIND'}</span><h3>{flipped?card.back:card.front}</h3>{flipped&&<blockquote>{card.quote}</blockquote>}<small><RotateCcw size={14}/>Click to {flipped?'see question':'reveal answer'}</small></button>{flipped?<div className="review-ratings">{[['again','Again · tomorrow'],['good','Got it · later'],['easy','Easy · much later']].map(([rating,label])=><button className={rating==='good'?'primary':'secondary'} disabled={busy} key={rating} onClick={async()=>{setBusy(true);try{await api('review','POST',{deckId:deck.id,cardId:card.id,rating});setReviewed(x=>[...x,card.id]);setFlipped(false);await onRefresh()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}}>{label}</button>)}</div>:<p className="center muted">Try recalling the answer before you turn the card.</p>}</>:<div className="empty"><Check size={40}/><h2>A little more learned.</h2><p>No more cards due in this set. Your next review dates are saved.</p><button className="secondary" onClick={()=>{setAll(true);setReviewed([])}}>Practice all cards</button></div>}</section>;
 if(result)return <section className="glass player">{top}<div className="test-result"><span className="eyebrow">PRACTICE COMPLETE</span><strong>{Math.round(result.score/result.total*100)}<small>%</small></strong><p>{result.score} of {result.total} correct. Every attempt is a step forward.</p></div>{result.questions.map((question,i)=><div className="question-result" key={question.id}><span className={result.answers[i]===question.answer?'correct':'error'}>{result.answers[i]===question.answer?'Correct':'Review this'} · Question {i+1}</span><h3>{question.prompt}</h3>{question.options.map((o,j)=><div className={'answer-explanation '+(j===question.answer?'right':'')} key={j}><strong>{String.fromCharCode(65+j)}. {o}{j===question.answer?' ✓':''}{j===result.answers[i]?' — your choice':''}</strong><p>{question.explanations[j]}</p></div>)}<blockquote>{question.quote}</blockquote></div>)}</section>;
 return <section className="glass player">{top}{mode==='test'&&!started?<div className="empty"><Timer size={35}/><h2>Ready for a deeper challenge?</h2><p>{deck.questions.length} AP-style questions · {deck.questions.length*2} minutes<br/>Explanations appear after you submit. This is independent practice, not an official AP exam.</p><button className="primary" onClick={()=>setStarted(true)}>Start test<ArrowRight size={16}/></button></div>:<><div className="question-progress"><span>Question {index+1} of {deck.questions.length}</span>{mode==='test'&&<strong><Timer size={16}/>{Math.floor(seconds/60)}:{(seconds%60).toString().padStart(2,'0')}</strong>}<span>{answers.filter(a=>a>=0).length} answered</span></div><div className="progress-track"><span style={{width:(index+1)/deck.questions.length*100+'%'}}/></div><h3 className="question-prompt">{q.prompt}</h3><div className="answer-options">{q.options.map((o,i)=><button className={'answer-option '+(answers[index]===i?'chosen':'')+(mode==='quiz'&&answers[index]>=0&&q.answer===i?' right':'')} key={i} onClick={()=>setAnswers(a=>a.map((v,j)=>j===index?i:v))} disabled={mode==='quiz'&&answers[index]>=0}><b>{String.fromCharCode(65+i)}</b>{o}</button>)}</div>{mode==='quiz'&&answers[index]>=0&&<div className="explanation"><h3 className={answers[index]===q.answer?'correct':'error'}>{answers[index]===q.answer?'You’ve got it.':'Let’s look at the reasoning.'}</h3>{q.options.map((o,i)=><p key={i}><strong>{String.fromCharCode(65+i)}{i===q.answer?' · Correct':''}.</strong> {q.explanations[i]}</p>)}<blockquote>{q.quote}</blockquote></div>}<div className="question-nav"><button className="secondary" disabled={index===0} onClick={()=>setIndex(index-1)}><ArrowLeft size={16}/>Previous</button>{index<deck.questions.length-1?<button className="primary" onClick={()=>setIndex(index+1)}>Next question<ArrowRight size={16}/></button>:<button className="primary" disabled={busy} onClick={submit}>{busy?'Saving results…':'Submit & see results'}<Check size={16}/></button>}</div><div className="question-dots">{deck.questions.map((_,i)=><button className={answers[i]>=0?'answered':''} aria-label={'Go to question '+(i+1)} key={i} onClick={()=>setIndex(i)}>{i+1}</button>)}</div></>}</section>
}
function StudyGame({deck,mode}:{deck:Deck;mode:string}){
 const [round,setRound]=useState(0),[pairs,setPairs]=useState(()=>shuffle(deck.cards).slice(0,6)),[right,setRight]=useState(()=>shuffle(pairs)),[leftPick,setLeftPick]=useState(''),[matched,setMatched]=useState<string[]>([]),[score,setScore]=useState(0),[lives,setLives]=useState(3),[time,setTime]=useState(20),[feedback,setFeedback]=useState(''),[running,setRunning]=useState(false);
 const current=deck.cards[round%deck.cards.length];const [choices,setChoices]=useState(()=>shuffle([current,...shuffle(deck.cards.filter(c=>c.id!==current.id)).slice(0,3)]));
 const next=()=>{const n=(round+1)%deck.cards.length;setRound(round+1);setChoices(shuffle([deck.cards[n],...shuffle(deck.cards.filter(c=>c.id!==deck.cards[n].id)).slice(0,3)]));setTime(20)};
 useEffect(()=>{if(mode!=='crash'||!running||lives<=0)return;const t=setInterval(()=>setTime(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[mode,running,lives]);
 useEffect(()=>{if(time===0&&running){setLives(v=>v-1);setFeedback('Time ran out. '+current.front+': '+current.back);next()}},[time,running]);
 if(mode==='match')return <><p className="center muted">Pick a prompt, then its matching explanation. {matched.length} / {pairs.length} matched</p><div className="match-board"><div>{pairs.map(c=><button key={c.id} className={'match-tile '+(leftPick===c.id?'chosen':'')+(matched.includes(c.id)?' matched':'')} disabled={matched.includes(c.id)} onClick={()=>setLeftPick(c.id)}>{c.front}{matched.includes(c.id)&&<Check size={16}/>}</button>)}</div><div>{right.map(c=><button key={c.id} className={'match-tile '+(matched.includes(c.id)?' matched':'')} disabled={!leftPick||matched.includes(c.id)} onClick={()=>{if(leftPick===c.id){setMatched(m=>[...m,c.id]);setFeedback('A perfect match.')}else setFeedback('Not quite. Try another explanation.');setLeftPick('')}}>{c.back}</button>)}</div></div><p className="center" aria-live="polite">{feedback}</p>{matched.length===pairs.length&&<div className="empty"><h3>Everything connected.</h3><button className="primary" onClick={()=>{const p=shuffle(deck.cards).slice(0,6);setPairs(p);setRight(shuffle(p));setMatched([]);setFeedback('')}}>Play again<RotateCcw size={16}/></button></div>}</>;
 return <><div className="game-status"><span>Score <b>{score}</b></span><span>Lives <b>{lives}</b></span><button className="secondary" onClick={()=>setRunning(!running)}>{running?<Pause size={15}/>:<Play size={15}/>} {running?'Pause':'Play'}</button></div>{lives>0?<><div className="crash-track"><div className="falling-term" style={{transform:`translateY(${(20-time)*7}px)`}}>{current.front}</div><div className="crash-floor">{time}s before impact</div></div><p className="center muted">Choose the correct explanation before the prompt hits the floor.</p><div className="crash-choices">{choices.map(c=><button className="secondary" disabled={!running} key={c.id} onClick={()=>{if(c.id===current.id){setScore(s=>s+10);setFeedback('Saved! '+current.back)}else{setLives(l=>l-1);setFeedback('The correct explanation: '+current.back)}next()}}>{c.back}</button>)}</div></>:<div className="empty"><h2>Round complete.</h2><p>{score} points. Take another run at it.</p><button className="primary" onClick={()=>{setLives(3);setScore(0);next();setRunning(true)}}>Play again</button></div>}<p className="game-feedback" aria-live="polite">{feedback}</p></>
}
export {default as Brainrot} from './focus-video';
